# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ps_match1 <- function(x) {
    .Call(`_egpkg_ps_match1`, x)
}

ps_match2 <- function(x) {
    .Call(`_egpkg_ps_match2`, x)
}

ps_match3 <- function(x) {
    .Call(`_egpkg_ps_match3`, x)
}

#' Hello world from Rcpp
#' @return A list with two vectors (`x`, `y`).
#' @examples
#' rcpp_hello_world()
#' @export
rcpp_hello_world <- function() {
    .Call(`_egpkg_rcpp_hello_world`)
}

